version: '3'
services:

  app:
    image: homation:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3111:3111"
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
